language: node_js
node_js:
  - "4"
before_script:
  - npm install -g coveralls
script:
  - make ci
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#brass-monkey"
after_success:
  - cat ./coverage/lcov.info | coveralls