language: node_js
node_js:
  - "4"
  - "6"
  - "8"
before_script:
  - npm install -g coveralls
  - npm install -g szero
script:
  - make ci
branches:
  only:
    - master
notifications:
  irc: "irc.freenode.org#bucharest-gold"
after_success:
  - npm run coverage
  - cat ./coverage/lcov.info | coveralls
